globalThis._importMeta_={url:import.meta.url,env:process.env};import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/node-fetch-native/dist/polyfill.mjs';
export { l as localFetch } from './chunks/nitro/nitro-prerenderer.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/h3/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/ofetch/dist/node.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/destr/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/unenv/runtime/fetch/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/hookable/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/scule/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/klona/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/defu/dist/defu.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/ohash/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/ufo/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/unstorage/dist/index.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/unstorage/drivers/fs.mjs';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/radix3/dist/index.mjs';
import 'node:fs';
import 'node:url';
import 'file:///Users/ivana/projects/fem/interactive-details-form/node_modules/pathe/dist/index.mjs';
//# sourceMappingURL=index.mjs.map
